package CORBAImplementation;


/**
* CORBAImplementation/CORBAImplementation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBAImplementation.idl
* Thursday, July 26, 2018 5:58:13 o'clock PM EDT
*/

public interface CORBAImplementation extends CORBAImplementationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBAImplementation
