package CORBAImplementation;


/**
* CORBAImplementation/CORBAImplementationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBAImplementation.idl
* Thursday, July 26, 2018 5:58:13 o'clock PM EDT
*/

public interface CORBAImplementationOperations 
{
  boolean createTRecord (String managerID, String recordID, String fName, String lName, String address, String phone, String specialization, String location);
  String getRecordCounts ();
  boolean editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean createSRecord (String managerID, String recordID, String fName, String lName, String coursesRegistered, boolean status, String statusDate);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface CORBAImplementationOperations
