package FrontEndImplementation;


/**
* FrontEndImplementation/FrontEndImplementation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndImplementation.idl
* Thursday, July 26, 2018 5:58:19 o'clock PM EDT
*/

public interface FrontEndImplementation extends FrontEndImplementationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndImplementation
