package FrontEndImplementation;

/**
* FrontEndImplementation/FrontEndImplementationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Thursday, July 26, 2018 5:58:19 o'clock PM EDT
*/

public final class FrontEndImplementationHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndImplementation value = null;

  public FrontEndImplementationHolder ()
  {
  }

  public FrontEndImplementationHolder (FrontEndImplementation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndImplementationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndImplementationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndImplementationHelper.type ();
  }

}
